export FLASK_APP="org.boltlinux.repository.flaskapp:app"
export FLASK_STATIC_URL_PATH=""
export FLASK_STATIC_FOLDER="ui/_site"
export FLASK_ROOT_PATH="."
export PYTHONPATH="`pwd`/lib"
export PATH="`pwd`/bin:$PATH"
